// Re-export generated protobuf code
// Generated by tonic-build from proto/swarm.proto
// Requires protoc to be installed during build

#![allow(clippy::all)]
#![allow(dead_code)]

tonic::include_proto!("talon.swarm");
