// Re-export generated protobuf code
// Generated by tonic-build from proto/swarm.proto
// Falls back to pre-generated code when protoc is not available

#![allow(clippy::all)]
#![allow(dead_code)]

// Use pre-generated proto code (proto_generated.rs)
// When protoc is available, tonic::include_proto! would be used instead
// For now, we use the pre-generated file for portability
pub use super::proto_generated::*;
