use std::collections::HashMap;

pub struct PoCWeaponizer {
    pub target_binary: String,
    pub exploit_script: String,
    pub parameters: HashMap<String, String>,
}

impl PoCWeaponizer {
    pub fn new(target_binary: &str, exploit_script: &str) -> Self {
        PoCWeaponizer {
            target_binary: target_binary.to_string(),
            exploit_script: exploit_script.to_string(),
            parameters: HashMap::new(),
        }
    }

    pub fn parameterize(&mut self) {
        self.parameters
            .insert("TARGET_HOST".to_string(), "{{TARGET_HOST}}".to_string());
        self.parameters
            .insert("TARGET_PORT".to_string(), "{{TARGET_PORT}}".to_string());
        self.parameters
            .insert("CALLBACK_HOST".to_string(), "{{CALLBACK_HOST}}".to_string());
        self.parameters
            .insert("CALLBACK_PORT".to_string(), "{{CALLBACK_PORT}}".to_string());
    }

    pub fn generate_python_wrapper(&self) -> Result<String, String> {
        let mut script = String::new();
        script.push_str("#!/usr/bin/env python3\n");
        script.push_str("# Weaponized exploit generated by TALON Framework\n\n");
        script.push_str("import argparse\n");
        script.push_str("import subprocess\n\n");
        script.push_str("def main():\n");
        script.push_str("    parser = argparse.ArgumentParser(description='Weaponized exploit')\n");
        script.push_str("    parser.add_argument('--target', required=True, help='Target host')\n");
        script.push_str(
            "    parser.add_argument('--port', type=int, required=True, help='Target port')\n",
        );
        script.push_str("    args = parser.parse_args()\n\n");
        script.push_str("    exploit = '''");
        script.push_str(&self.exploit_script);
        script.push_str("'''\n\n");
        script.push_str("    subprocess.run(['talon', 'run', '-'], input=exploit, text=True)\n\n");
        script.push_str("if __name__ == '__main__':\n");
        script.push_str("    main()\n");
        Ok(script)
    }

    pub fn generate_metasploit_module(&self) -> Result<String, String> {
        let mut module = String::new();
        module.push_str("##\n");
        module.push_str("# Metasploit module generated by TALON Framework\n");
        module.push_str("##\n\n");
        module.push_str("class MetasploitModule < Msf::Exploit::Remote\n");
        module.push_str("  Rank = NormalRanking\n\n");
        module.push_str("  def initialize(info = {})\n");
        module.push_str("    super(update_info(info,\n");
        module.push_str(&format!("      'Name' => '{}',\n", self.target_binary));
        module.push_str("      'Description' => 'TALON-generated exploit',\n");
        module.push_str("      'Author' => ['TALON Framework'],\n");
        module.push_str("      'Platform' => 'linux',\n");
        module.push_str("      'Targets' => [['Automatic', {}]]\n");
        module.push_str("    ))\n");
        module.push_str("  end\n\n");
        module.push_str("  def exploit\n");
        module.push_str("    # Implementation here\n");
        module.push_str("  end\n");
        module.push_str("end\n");
        Ok(module)
    }

    pub fn add_bad_char_encoder(&mut self, bad_chars: &[u8]) {
        let encoder_code = format!(
            "\nlet bad_chars = {:?}\nlet payload = encode_alphanumeric(raw_payload, bad_chars)\n",
            bad_chars
        );
        self.exploit_script.push_str(&encoder_code);
    }

    pub fn add_multi_target_support(&mut self, targets: Vec<(String, u16)>) {
        let mut target_code = String::from("\nlet targets = [\n");
        for (host, port) in targets {
            target_code.push_str(&format!("    (\"{}\", {}),\n", host, port));
        }
        target_code.push_str("]\n\nfor (host, port) in targets {\n");
        target_code.push_str("    exploit_target(host, port)\n");
        target_code.push_str("}\n");
        self.exploit_script.push_str(&target_code);
    }
}

impl Default for PoCWeaponizer {
    fn default() -> Self {
        Self::new("", "")
    }
}
